services:
  # TCP storage server (C++ server)
  tcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - tcp_storage:/usr/src/mytest/app

  # Web API server (Node.js + Express)
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:3000"
    environment:
      - TCP_HOST=tcp-server
      - CONNECTION_STRING=mongodb://db:27017/googleDriveDB
      - PORT=3000
    depends_on:
      - tcp-server
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/web         

  # React Frontend
  react-frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.react
    ports:
      - "3001:3000"
    volumes:
      - ./web:/usr/src/app        
      - /usr/src/app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true
      - GENERATE_SOURCEMAP=false  
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_OPTIONS=--max-old-space-size=4096
    depends_on:
      - web-server

  # MongoDB Database service
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - drive-db-data:/data/db

volumes:
  tcp_storage:
  drive-db-data: