services:
  # TCP storage server (C++ server)
  tcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - tcp_storage:/usr/src/mytest/app

  # Web API server (Node.js + Express)
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:3000"
    environment:
      - TCP_HOST=tcp-server
    depends_on:
      - tcp-server
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/web          # מונע מהנוד לנסות "לקרוא" את תיקיית הריאקט בטעות

  # React Frontend
  react-frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.react
    ports:
      - "3001:3000"
    volumes:
      - ./web:/usr/src/app         # מקשר את קוד המקור שלך לתוך הקונטיינר
      - /usr/src/app/node_modules  # "מגן" על התיקייה הפנימית של הספריות
    environment:
      - CHOKIDAR_USEPOLLING=true   # קריטי לעדכון אוטומטי ב-Windows
      - WDS_SOCKET_PORT=3001
    depends_on:
      - web-server

volumes:
  tcp_storage: