import { StyleSheet } from 'react-native';
import { Colors, Fonts } from '../constants/theme';

export const layoutStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  headerContainer: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: Colors.light.surface, 
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.border,
    elevation: 2, 
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  backButton: {
    marginRight: 15,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    fontSize: 24,
    color: Colors.light.primary,
    fontWeight: 'bold',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: Fonts.sans,
    flex: 1, 
  },
  safeArea: {
    backgroundColor: Colors.light.primary,
  },
  topBar: {
    height: 60,
    justifyContent: 'center',
    paddingHorizontal: 20,
    backgroundColor: Colors.light.primary,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
  },
  topBarText: {
    color: Colors.light.surface,
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: Fonts.sans,
  },
  tabBarCustom: {
    height: 85,
    paddingBottom: 25,
    paddingTop: 10,
    backgroundColor: Colors.light.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.light.border,
    elevation: 0,
    shadowOpacity: 0,
  },
  activeColor: Colors.light.tabActive,
  inactiveColor: Colors.light.tabInactive,
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 100, 
    backgroundColor: Colors.light.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  cameraFab: {
    bottom: 175, 
    right: 26,  
    width: 48, 
    height: 48, 
    borderRadius: 24,
    backgroundColor: Colors.light.primary, 
    opacity: 0.9, 
    zIndex: 10,
  },
  optionsContainer: {
    position: 'absolute',
    right: 20,
    bottom: 240, 
    zIndex: 9,
    alignItems: 'flex-end',
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  iconCircle: {
    backgroundColor: Colors.light.primary,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  optionText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    backgroundColor: Colors.light.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.light.border,
    overflow: 'hidden',
  },
});

