import { StyleSheet } from 'react-native';
import { Fonts } from '../constants/theme';

export const createLayoutStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  safeArea: {
    backgroundColor: theme.background,
  },
  topBar: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: theme.surface, 
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    elevation: 2, 
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  backButton: {
    marginRight: 15,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    fontSize: 24,
    color: theme.primary,
    fontWeight: 'bold',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.textMain,
    fontFamily: Fonts.sans,
    flex: 1, 
  },
  topBarContainer: {
    flexDirection: 'row',     
    alignItems: 'center',     
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,                 
    borderBottomWidth: 1,
  },
  iconButton: {
    padding: 4,
  },
  searchContainer: {
    flex: 1,                 
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,      
    paddingHorizontal: 16,
    borderRadius: 30,       
  },
  searchPlaceholder: {
    fontSize: 16,
    marginLeft: 8,
    fontFamily: Fonts.sans,   
  },
  rightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12, 
  },
  profileButton: {
    padding: 2,
  },
  tabBarCustom: {
    height: 85,
    paddingBottom: 25,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    elevation: 0,
    shadowOpacity: 0,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 100, 
    backgroundColor: theme.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  cameraFab: {
    bottom: 175, 
    right: 26,  
    width: 48, 
    height: 48, 
    borderRadius: 24,
    backgroundColor: theme.primary, 
    opacity: 0.9, 
    zIndex: 10,
  },
  optionsContainer: {
    position: 'absolute',
    right: 20,
    bottom: 240, 
    zIndex: 9,
    alignItems: 'flex-end',
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  iconCircle: {
    backgroundColor: theme.primary,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  optionText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.textMain,
    backgroundColor: theme.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: 'hidden',
  },
});

export const createTabColors = (theme) => ({
  active: theme.primary,
  inactive: theme.textMuted,
});
